"""
PLOTTING_LLM_FINAL.py  —  AE4135 Rotor/Wake Aerodynamics, Assignment 2
BEM vs Lifting-Line comparison + Lifting-Line results & sensitivity plots.

Authors: Douwe de Jong (5313899), Martijn van Leeuwen (5614422)
================================================================
Loads:
    bem_results.npz      — from BEM_FINAL.py (previous assignment)
    LLM_results.npz      — from LLM_FINAL.py  (frozen-vortex-wake / lifting line)

Produces:
    Chapter 4  — Lifting-Line (LL) results  +  BEM / LL comparison
                 (φ, α, a, a', C_n, C_t, circulation, C_T(λ), C_P(λ))
    Chapter 5  — LL sensitivity study
                   • wake convection induction a_w  (+ self-consistency)
                   • blade discretisation N + cosine/constant spacing
                   • azimuthal step Δψ
                   • wake length N_wake

The LL-only figures reproduce the current figures generated by LLM_FINAL.py
The BEM/LLM comparison figures are unique to this combined script.

Saves the resulting plots to LLM_combined_plots/ as PDF files.  

NOTE — a few of the solver's sensitivity figures depend on per-case
wall-clock timing and inner-loop convergence flags.  Those quantities are NOT
written to LLM_results.npz, so the timing plots (Sens_*_d2 / e1 / e2) and the
converged/not-converged marker split are omitted here; they remain available
by running LLM_FINAL.py directly. 

Run:  python PLOTTING_LLM_FINAL.py
"""

import os
import sys
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

# =============================================================================
# 0.  PATHS 
# =============================================================================

_HERE   = os.path.dirname(os.path.abspath(__file__))
BEM_NPZ = os.path.join(_HERE, "bem_results.npz")
LL_NPZ  = os.path.join(_HERE, "LLM_results.npz")
OUT_DIR = os.path.join(_HERE, "LLM_combined_plots")
os.makedirs(OUT_DIR, exist_ok=True)

SHOW_PLOTS = False   

# =============================================================================
# 1.  GLOBAL PLOT STYLE 
# =============================================================================

# ── Font size tiers (single source of truth for legends/annotations) ──
font_size_small  = 9    # crowded legends pushed outside the axes
font_size_medium = 10    # spanwise-sweep legends, in-axes note boxes
font_size_big    = 11    # comparison/sensitivity legends, direction-arrow labels

mpl.rcParams.update({
    "text.usetex"       : False,
    "font.family"       : "serif",
    "font.serif"        : ["CMU Serif", "Computer Modern Roman",
                           "Latin Modern Roman", "DejaVu Serif"],
    "mathtext.fontset"  : "cm",
    "axes.labelsize"    : 14,
    "legend.fontsize"   : 11,
    "xtick.labelsize"   : 10,
    "ytick.labelsize"   : 10,
    "axes.titlesize"    : 12,
    "savefig.bbox"      : "tight",
    "savefig.pad_inches": 0.02,
    "legend.frameon"    : True,
})

_CB_PALETTE = sns.color_palette("colorblind").as_hex() + [
    '#8b0000',  # dark red
    '#556b2f',  # dark olive green
    '#4b0082',  # indigo
    '#ff6347',  # tomato
    '#20b2aa',  # light sea green
    '#8b4513',  # saddle brown
    '#2f4f4f',  # dark slate gray
    '#9400d3',  # dark violet
    '#6a5acd',  # slate blue
    '#b8860b',  # dark goldenrod
]
_CB = _CB_PALETTE   # short alias

# Fixed per-TSR colours 
_TSR_COL = {6: _CB[0], 8: _CB[1], 10: _CB[2]}

def _sens_color(idx):
    return _CB_PALETTE[idx % len(_CB_PALETTE)]

# Distribution styling for the discretisation study 
_DIST_STYLE = {
    "cosine":   {"color": "#0173b2", "ls": "-",  "marker": "o", "label": "Cosine"},
    "constant": {"color": "#d55e00", "ls": "--", "marker": "s", "label": "Constant"},
}

# =============================================================================
# 2.  SAVE HELPER
# =============================================================================

def _savefig(fname: str) -> None:
    stem = fname[:-4] if fname.endswith(".pdf") else fname
    path = os.path.join(OUT_DIR, stem + ".pdf")
    plt.savefig(path)
    print(f"  Saved: {os.path.basename(path)}")
    if SHOW_PLOTS:
        plt.show()
    else:
        plt.close()

# =============================================================================
# 3.  LOAD DATA
# =============================================================================

print(f"Loading BEM results  → {BEM_NPZ}")
if not os.path.exists(BEM_NPZ):
    sys.exit(f"  ERROR: {BEM_NPZ} not found. Run BEM_FINAL.py first.")
B = np.load(BEM_NPZ, allow_pickle=False)

print(f"Loading LL  results  → {LL_NPZ}")
if not os.path.exists(LL_NPZ):
    sys.exit(f"  ERROR: {LL_NPZ} not found. Run LLM_FINAL.py first.")
L = np.load(LL_NPZ, allow_pickle=False)

TSR_SPAN = [6, 8, 10]

# ── BEM per-TSR arrays --------------------------------------------------------
def _bem(tsr: int) -> np.ndarray:
    key = f"sweep_res_{tsr}"
    if key not in B.files:
        sys.exit(f"  ERROR: key '{key}' missing from {BEM_NPZ}")
    return B[key]

bem = {tsr: _bem(tsr) for tsr in TSR_SPAN}

# BEM scalar performance (wide TSR sweep for the CT/CP-λ comparison)
bem_tsrs_perf = B["sweep_tsrs_perf"] if "sweep_tsrs_perf" in B.files else np.array(TSR_SPAN, dtype=float)
bem_CT_perf   = B["tsr_CT_perf"]     if "tsr_CT_perf"    in B.files else np.array([B["tsr_CT"][i] for i in range(3)])
bem_CP_perf   = B["tsr_CP_perf"]     if "tsr_CP_perf"    in B.files else np.array([B["tsr_CP"][i] for i in range(3)])

# BEM scalar CT/CP at the 3 span TSRs (for the comparison table)
bem_CT_span = {tsr: float(B["tsr_CT"][i]) for i, tsr in enumerate(TSR_SPAN)} if "tsr_CT" in B.files else {}
bem_CP_span = {tsr: float(B["tsr_CP"][i]) for i, tsr in enumerate(TSR_SPAN)} if "tsr_CP" in B.files else {}

# =============================================================================
# 3b.  LL CONFIGURATION 
# =============================================================================

def _lcfg(key, default):
    return float(L[key]) if key in L.files else float(default)

Radius        = _lcfg("cfg_Radius",         50.0)
NBlades       = int(_lcfg("cfg_NBlades",     3))
U0            = _lcfg("cfg_U0",             10.0)
rho           = _lcfg("cfg_rho",            1.0)
RootLocation  = _lcfg("cfg_RootLocation_R", 0.2)
TipLocation   = _lcfg("cfg_TipLocation_R",  1.0)
N_PANELS      = int(_lcfg("cfg_N_PANELS",   20))
N_WAKE        = int(_lcfg("cfg_N_WAKE",      5))
DPSI_DEG      = _lcfg("cfg_DPSI_DEG",       10.0)
A_WAKE        = _lcfg("cfg_A_WAKE",          0.25)

norm_val = 0.5 * rho * U0**2 * Radius   # loading normalisation (LL and BEM, ρ=1)
norm_ll  = norm_val
norm_bem = norm_val

# ── LL per-TSR arrays ---------------------------------------------------------
def _ll(tsr: int) -> np.ndarray:
    key = f"sweep_res_{tsr}"
    if key not in L.files:
        sys.exit(f"  ERROR: key '{key}' missing from {LL_NPZ}")
    return L[key]

ll = {tsr: _ll(tsr) for tsr in TSR_SPAN}

# LL scalar performance (wide TSR sweep, λ=4..12)
ll_tsrs_perf = L["perf_tsrs"] if "perf_tsrs" in L.files else np.array(TSR_SPAN, dtype=float)
ll_CT_perf   = L["perf_CT"]   if "perf_CT"   in L.files else np.array([])
ll_CP_perf   = L["perf_CP"]   if "perf_CP"   in L.files else np.array([])

# LL scalar CT/CP at the 3 span TSRs
ll_CT_span = {tsr: float(L["tsr_CT"][i]) for i, tsr in enumerate(TSR_SPAN)} if "tsr_CT" in L.files else {}
ll_CP_span = {tsr: float(L["tsr_CP"][i]) for i, tsr in enumerate(TSR_SPAN)} if "tsr_CP" in L.files else {}

# =============================================================================
# 3c.  SCALAR CT / CP RECOMPUTATION FROM A SPANWISE RESULT ARRAY
# =============================================================================

def _panel_edges(N, dist):
    r_root = RootLocation * Radius
    r_tip  = TipLocation  * Radius
    if dist == "cosine":
        theta = np.linspace(0.0, np.pi, N + 1)
        return r_root + 0.5 * (r_tip - r_root) * (1.0 - np.cos(theta))
    return np.linspace(r_root, r_tip, N + 1)

def _ct_cp_from_res(res, tsr, dist):
    """Integrate F_n, F_t over the span to get C_T, C_P (exact reconstruction)."""
    N     = res.shape[0]
    dr    = np.diff(_panel_edges(N, dist))
    r     = res[:, 2] * Radius
    Omega = U0 * tsr / Radius
    A     = np.pi * Radius**2
    T  = NBlades * np.sum(res[:, 3] * dr)
    Q  = NBlades * np.sum(res[:, 4] * r * dr)
    P  = Omega * Q
    CT = T / (0.5 * rho * U0**2 * A)
    CP = P / (0.5 * rho * U0**3 * A)
    return CT, CP

# =============================================================================
# 3d.  SENSITIVITY ARRAY LOADERS
# =============================================================================

def _lget(key, default=None):
    return L[key] if key in L.files else (np.array([]) if default is None else default)

sens_aw_vals    = _lget("sens_aw_vals")
sens_aw_CT      = _lget("sens_aw_CT")
sens_aw_CP      = _lget("sens_aw_CP")

sens_dpsi_vals  = _lget("sens_dpsi_vals")
sens_dpsi_CT    = _lget("sens_dpsi_CT")
sens_dpsi_CP    = _lget("sens_dpsi_CP")

sens_nwake_vals = _lget("sens_nwake_vals")
sens_nwake_CT   = _lget("sens_nwake_CT")
sens_nwake_CP   = _lget("sens_nwake_CP")

sens_N_vals     = _lget("sens_N_vals")
sens_N_CT_cos   = _lget("sens_N_CT_cosine")
sens_N_CP_cos   = _lget("sens_N_CP_cosine")

print(f"  LL sensitivity a_w   : {sens_aw_vals}")
print(f"  LL sensitivity dpsi  : {sens_dpsi_vals}")
print(f"  LL sensitivity nwake : {sens_nwake_vals}")
print(f"  LL sensitivity N     : {sens_N_vals}")

def _scan_suffixed(prefix):
    out, plen = {}, len(prefix)
    for k in L.files:
        if k.startswith(prefix):
            try:
                out[round(float(k[plen:]), 6)] = k
            except ValueError:
                pass
    return out

_aw_keys    = _scan_suffixed("sens_aw_res_")
_dpsi_keys  = _scan_suffixed("sens_dpsi_res_")
_nwake_keys = _scan_suffixed("sens_nwake_res_")

def _aw_res(v):    return L[_aw_keys[round(float(v), 6)]]    if round(float(v), 6) in _aw_keys    else None
def _dpsi_res(v):  return L[_dpsi_keys[round(float(v), 6)]]  if round(float(v), 6) in _dpsi_keys  else None
def _nwake_res(v): return L[_nwake_keys[round(float(v), 6)]] if round(float(v), 6) in _nwake_keys else None

def _disc_res(N, dist):
    key = f"sens_disc_res_{int(N)}_{dist}"
    return L[key] if key in L.files else None

# Convenience column accessors for spanwise sensitivity curves
def _rR(res): return res[:, 2]
def _a(res):  return res[:, 0]
def _Cn(res): return res[:, 3] / norm_val

# =============================================================================
# 3e.  DIRECTION-ARROW ANNOTATION HELPER 
# =============================================================================

def _annotate_increasing_direction(ax, x_data_list, y_data_list,
                                   label="increasing", color="#333333",
                                   margin_frac=0.08, force_direction=None,
                                   x_pos=None, y_pos=None):
    """Place a single-headed arrow showing the direction in which curves shift
    as the swept parameter increases."""
    if len(y_data_list) < 2:
        return

    # ── Horizontal (left) arrow — drawn at a fixed y position ────────────
    if force_direction == 'left':
        ax_xmin, ax_xmax = ax.get_xlim()
        ax_ymin, ax_ymax = ax.get_ylim()
        x_range = ax_xmax - ax_xmin
        y_range = ax_ymax - ax_ymin

        if y_pos is not None:
            y_level = float(y_pos)
        else:
            x_ref   = x_data_list[0]
            y_first = y_data_list[0]
            y_last  = np.interp(x_ref, x_data_list[-1], y_data_list[-1])
            spread  = np.abs(y_last - y_first)
            idx_max = int(np.argmax(spread))
            y_level = float(y_first[idx_max])
            y_level = float(np.clip(y_level,
                                    ax_ymin + 0.08 * y_range,
                                    ax_ymax - 0.08 * y_range))

        x_tail = ax_xmax - 0.05 * x_range
        x_head = ax_xmin + 0.05 * x_range
        ax.annotate("", xy=(x_head, y_level), xytext=(x_tail, y_level),
                    arrowprops=dict(arrowstyle="->", color=color, lw=1.5))
        x_mid   = 0.5 * (x_tail + x_head)
        y_label = y_level + 0.04 * y_range
        ax.text(x_mid, y_label, label, fontsize=font_size_big, color=color,
                va="bottom", ha="center",
                bbox=dict(boxstyle="round,pad=0.2", fc="white",
                          ec=color, alpha=0.75, lw=0.8))
        return

    # ── Vertical arrow ────────────────────────────────────────────────────
    x_ref   = x_data_list[0]
    y_first = y_data_list[0]
    y_last  = np.interp(x_ref, x_data_list[-1], y_data_list[-1])

    spread  = np.abs(y_last - y_first)
    if x_pos is not None:
        idx_max = int(np.argmin(np.abs(x_ref - x_pos)))
    else:
        idx_max = int(np.argmax(spread))
    x_arrow = float(x_ref[idx_max])

    y0 = float(y_first[idx_max])
    y1 = float(y_last[idx_max])

    if force_direction == 'up':
        direction_up = True
    elif force_direction == 'down':
        direction_up = False
    else:
        direction_up = y1 > y0

    y_low, y_high = min(y0, y1), max(y0, y1)
    ax_ymin, ax_ymax = ax.get_ylim()
    y_range = ax_ymax - ax_ymin
    offset  = margin_frac * y_range

    if direction_up:
        y_tail, y_head = y_low - offset, y_high + offset
    else:
        y_tail, y_head = y_high + offset, y_low - offset

    guard  = 0.02 * y_range
    y_tail = float(np.clip(y_tail, ax_ymin + guard, ax_ymax - guard))
    y_head = float(np.clip(y_head, ax_ymin + guard, ax_ymax - guard))

    ax.annotate("", xy=(x_arrow, y_head), xytext=(x_arrow, y_tail),
                arrowprops=dict(arrowstyle="->", color=color, lw=1.5))
    y_mid   = 0.5 * (y_tail + y_head)
    x_label = x_arrow + 0.03 * (ax.get_xlim()[1] - ax.get_xlim()[0])
    ax.text(x_label, y_mid, label, fontsize=font_size_big, color=color,
            va="center", ha="left",
            bbox=dict(boxstyle="round,pad=0.2", fc="white",
                      ec=color, alpha=0.75, lw=0.8))

# =============================================================================
# 4.  CHAPTER 4  —  LL RESULTS + BEM COMPARISON
# =============================================================================

print("\n" + "=" * 60)
print("Chapter 4 — LL results + BEM comparison")
print("=" * 60)

# ---------------------------------------------------------------------------
# 4.1  Inflow angle φ  and  angle of attack α
# ---------------------------------------------------------------------------

# ── LL only ───────────────────────────
for qty_col, ylabel, fname in [
        (7, r"$\phi$ [deg]",   "LL_1a_inflow_angle_vs_rR"),
        (6, r"$\alpha$ [deg]", "LL_1b_angle_of_attack_vs_rR")]:
    fig, ax = plt.subplots(figsize=(8, 5))
    for tsr in TSR_SPAN:
        ax.plot(ll[tsr][:, 2], ll[tsr][:, qty_col],
                color=_TSR_COL[tsr], lw=2, label=rf"$\lambda={tsr}$")
    ax.set_xlabel("r/R"); ax.set_ylabel(ylabel)
    ax.legend(); ax.grid(True)
    fig.tight_layout(); _savefig(fname)

# ── BEM vs LL comparison (subplots per TSR) ────────────────────────────────
for qty_col, ylabel, fname in [
        (7, r"$\phi$ [deg]",   "BEMvsLL_inflow_angle_vs_rR"),
        (6, r"$\alpha$ [deg]", "BEMvsLL_angle_of_attack_vs_rR")]:
    fig, axes = plt.subplots(1, 3, figsize=(14, 4), sharey=True)
    for ax, tsr in zip(axes, TSR_SPAN):
        ax.plot(ll[tsr][:, 2],  ll[tsr][:, qty_col],  color=_TSR_COL[tsr], lw=2, ls="-",
                label=rf"LLM ($\lambda={tsr}$)")
        ax.plot(bem[tsr][:, 2], bem[tsr][:, qty_col], color="k", lw=2, ls="--",
                label=rf"BEM ($\lambda={tsr}$)")
        ax.set_xlabel("r/R"); ax.legend(fontsize=font_size_big); ax.grid(True)
    axes[0].set_ylabel(ylabel)
    fig.tight_layout(); _savefig(fname)

# ---------------------------------------------------------------------------
# 4.2  Induction factors a, a'
# ---------------------------------------------------------------------------

for qty_col, ylabel, fname in [
        (0, r"$a$ [-]",  "LL_2a_axial_induction_vs_rR"),
        (1, r"$a'$ [-]", "LL_2b_tangential_induction_vs_rR")]:
    fig, ax = plt.subplots(figsize=(8, 5))
    for tsr in TSR_SPAN:
        ax.plot(ll[tsr][:, 2], ll[tsr][:, qty_col],
                color=_TSR_COL[tsr], lw=2, label=rf"$\lambda={tsr}$")
    ax.set_xlabel("r/R"); ax.set_ylabel(ylabel)
    ax.legend(); ax.grid(True)
    fig.tight_layout(); _savefig(fname)

for qty_col, ylabel, fname in [
        (0, r"$a$ [-]",  "BEMvsLL_axial_induction_vs_rR"),
        (1, r"$a'$ [-]", "BEMvsLL_tangential_induction_vs_rR")]:
    fig, axes = plt.subplots(1, 3, figsize=(14, 4), sharey=True)
    for ax, tsr in zip(axes, TSR_SPAN):
        ax.plot(ll[tsr][:, 2],  ll[tsr][:, qty_col],  color=_TSR_COL[tsr], lw=2, ls="-",
                label=rf"LLM ($\lambda={tsr}$)")
        ax.plot(bem[tsr][:, 2], bem[tsr][:, qty_col], color="k", lw=2, ls="--",
                label=rf"BEM ($\lambda={tsr}$)")
        ax.set_xlabel("r/R"); ax.legend(fontsize=font_size_big); ax.grid(True)
    axes[0].set_ylabel(ylabel)
    fig.tight_layout(); _savefig(fname)

# ---------------------------------------------------------------------------
# 4.3  Loading distributions  C_n, C_t   (normalised by ½ρU∞²R)
# ---------------------------------------------------------------------------

for qty_col, ylabel, fname in [
        (3, r"$C_n = F_n\,/\,(\frac{1}{2}\rho U_\infty^2 R)$", "LL_3a_normal_loading_Cn_vs_rR"),
        (4, r"$C_t = F_t\,/\,(\frac{1}{2}\rho U_\infty^2 R)$", "LL_3b_azimuthal_loading_Ct_vs_rR")]:
    fig, ax = plt.subplots(figsize=(8, 5))
    for tsr in TSR_SPAN:
        ax.plot(ll[tsr][:, 2], ll[tsr][:, qty_col] / norm_ll,
                color=_TSR_COL[tsr], lw=2, label=rf"$\lambda={tsr}$")
    ax.set_xlabel("r/R"); ax.set_ylabel(ylabel)
    ax.legend(); ax.grid(True)
    fig.tight_layout(); _savefig(fname)

for qty_col, ylabel, fname in [
        (3, r"$C_n$ [-]", "BEMvsLL_normal_loading_Cn_vs_rR"),
        (4, r"$C_t$ [-]", "BEMvsLL_azimuthal_loading_Ct_vs_rR")]:
    fig, axes = plt.subplots(1, 3, figsize=(14, 4), sharey=True)
    for ax, tsr in zip(axes, TSR_SPAN):
        ax.plot(ll[tsr][:, 2],  ll[tsr][:, qty_col]  / norm_ll,  color=_TSR_COL[tsr], lw=2, ls="-",
                label=rf"LLM ($\lambda={tsr}$)")
        ax.plot(bem[tsr][:, 2], bem[tsr][:, qty_col] / norm_bem, color="k", lw=2, ls="--",
                label=rf"BEM ($\lambda={tsr}$)")
        ax.set_xlabel("r/R"); ax.legend(fontsize=font_size_big); ax.grid(True)
    axes[0].set_ylabel(ylabel)
    fig.tight_layout(); _savefig(fname)

# ---------------------------------------------------------------------------
# 4.4  Circulation distribution
#      normalised by  π U∞² / (B Ω)
# ---------------------------------------------------------------------------

fig, ax = plt.subplots(figsize=(8, 5))
for tsr in TSR_SPAN:
    Omega  = U0 * tsr / Radius
    norm_G = np.pi * U0**2 / (NBlades * Omega)
    ax.plot(ll[tsr][:, 2], ll[tsr][:, 5] / norm_G,
            color=_TSR_COL[tsr], lw=2, label=rf"$\lambda={tsr}$")
ax.set_xlabel("r/R")
ax.set_ylabel(r"$\Gamma\,/\,(\pi U_\infty^2 / (B\,\Omega))$ [-]")
ax.legend(); ax.grid(True)
fig.tight_layout(); _savefig("LL_4_circulation_vs_rR")

# ---------------------------------------------------------------------------
# 4.5  Total performance C_T and C_P vs λ
# ---------------------------------------------------------------------------

# ── LL only ───────────────────────────
if len(ll_CT_perf) > 0:
    for vals, ylabel, fname, col in [
            (ll_CT_perf, r"$C_T$ [-]", "LL_5c_CT_vs_TSR", "#0173b2"),
            (ll_CP_perf, r"$C_P$ [-]", "LL_5d_CP_vs_TSR", "#029e73")]:
        fig, ax = plt.subplots(figsize=(9, 5))
        ax.plot(ll_tsrs_perf, vals, "o-", color=col, lw=2, ms=5, zorder=2)
        ax.set_xlabel(r"Tip-speed ratio $\lambda$ [-]")
        ax.set_ylabel(ylabel)
        ax.set_xlim(3.5, 12.5); ax.set_xticks(np.arange(4, 13, 1))
        ax.grid(True)
        fig.tight_layout(); _savefig(fname)

# ── BEM vs LL comparison ────────────────────────────────────────────────────
if len(ll_CT_perf) > 0:
    fig, ax = plt.subplots(figsize=(9, 5))
    ax.plot(ll_tsrs_perf,  ll_CT_perf,  "o-",  color="#0173b2", lw=2, ms=5, label="LLM")
    ax.plot(bem_tsrs_perf, bem_CT_perf, "s--", color="k",       lw=2, ms=5, label="BEM")
    ax.set_xlabel(r"Tip-speed ratio $\lambda$ [-]"); ax.set_ylabel(r"$C_T$ [-]")
    ax.set_xlim(3.5, 12.5); ax.set_xticks(np.arange(4, 13, 1))
    ax.legend(); ax.grid(True)
    fig.tight_layout(); _savefig("BEMvsLL_CT_vs_TSR")

    fig, ax = plt.subplots(figsize=(9, 5))
    ax.plot(ll_tsrs_perf,  ll_CP_perf,  "o-",  color="#029e73", lw=2, ms=5, label="LLM")
    ax.plot(bem_tsrs_perf, bem_CP_perf, "s--", color="k",       lw=2, ms=5, label="BEM")
    ax.axhline(16/27, color="grey", ls=":", lw=1.2, label="Betz limit")
    ax.set_xlabel(r"Tip-speed ratio $\lambda$ [-]"); ax.set_ylabel(r"$C_P$ [-]")
    ax.set_xlim(3.5, 12.5); ax.set_xticks(np.arange(4, 13, 1))
    ax.legend(); ax.grid(True)
    fig.tight_layout(); _savefig("BEMvsLL_CP_vs_TSR")

# ── Scalar CT/CP comparison table (printed to terminal) ─────────────────────
print("\n  CT / CP comparison table (LL vs BEM):")
print(f"  {'TSR':>4} {'CT_LL':>8} {'CT_BEM':>8} {'dCT%':>7} {'CP_LL':>8} {'CP_BEM':>8} {'dCP%':>7}")
print("  " + "-" * 56)
for tsr in TSR_SPAN:
    ct_ll  = ll_CT_span.get(tsr, float("nan"))
    ct_bem = bem_CT_span.get(tsr, float("nan"))
    cp_ll  = ll_CP_span.get(tsr, float("nan"))
    cp_bem = bem_CP_span.get(tsr, float("nan"))
    dct = (ct_ll - ct_bem) / ct_bem * 100 if ct_bem else float("nan")
    dcp = (cp_ll - cp_bem) / cp_bem * 100 if cp_bem else float("nan")
    print(f"  {tsr:>4} {ct_ll:>8.4f} {ct_bem:>8.4f} {dct:>+7.2f}% "
          f"{cp_ll:>8.4f} {cp_bem:>8.4f} {dcp:>+7.2f}%")

# =============================================================================
# 5.  CHAPTER 5  —  LL SENSITIVITY STUDY
# =============================================================================

print("\n" + "=" * 60)
print("Chapter 5 — LL sensitivity study")
print("=" * 60)

_BL_CT = float(ll_CT_span.get(8, float("nan")))
_BL_CP = float(ll_CP_span.get(8, float("nan")))

# ---------------------------------------------------------------------------
# 5.1  Wake convection induction  a_w   
# ---------------------------------------------------------------------------
print("\n  5.1 — convection induction (a_w)")

if len(sens_aw_vals) > 0:
    aw_arr  = np.asarray(sens_aw_vals, dtype=float)
    ct_arr  = np.asarray(sens_aw_CT,   dtype=float)
    cp_arr  = np.asarray(sens_aw_CP,   dtype=float)
    aw_res  = [_aw_res(v) for v in aw_arr]

    meana_arr = np.array([float(np.mean(r[:, 0])) if r is not None else np.nan
                          for r in aw_res])
    resid_arr = meana_arr - aw_arr

    try:
        sc_aw  = float(np.interp(0.0, resid_arr[::-1], aw_arr[::-1]))
        sc_CT  = float(np.interp(sc_aw, aw_arr, ct_arr))
        sc_CP  = float(np.interp(sc_aw, aw_arr, cp_arr))
        has_sc = True
        print(f"    Self-consistent a_w = {sc_aw:.4f}  CT={sc_CT:.4f}  CP={sc_CP:.4f}")
    except Exception:
        has_sc, sc_aw = False, A_WAKE

    # ── Sens_AW_1: CT vs a_w ──────────────────────────────────────────────
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(aw_arr, ct_arr, "o-", color="#0173b2", lw=2, ms=5, zorder=3)
    ax.axvline(A_WAKE, color="#d55e00", ls="--", lw=1.5, label=rf"Fixed $a_w = {A_WAKE:g}$")
    if has_sc:
        ax.axvline(sc_aw, color="#029e73", ls=":", lw=2, label=rf"Self-consistent $a_w = {sc_aw:.3f}$")
    ax.set_xlabel(r"Wake convection induction $a_w$ [-]"); ax.set_ylabel(r"$C_T$ [-]")
    ax.legend(fontsize=font_size_big); ax.grid(True)
    fig.tight_layout(); _savefig("Sens_AW_1_CT_vs_aw")

    # ── Sens_AW_2: CP vs a_w ──────────────────────────────────────────────
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(aw_arr, cp_arr, "o-", color="#029e73", lw=2, ms=5, zorder=3)
    ax.axvline(A_WAKE, color="#d55e00", ls="--", lw=1.5, label=rf"Fixed $a_w = {A_WAKE:g}$")
    if has_sc:
        ax.axvline(sc_aw, color="#0173b2", ls=":", lw=2, label=rf"Self-consistent $a_w = {sc_aw:.3f}$")
    ax.set_xlabel(r"Wake convection induction $a_w$ [-]"); ax.set_ylabel(r"$C_P$ [-]")
    ax.legend(fontsize=font_size_big); ax.grid(True)
    fig.tight_layout(); _savefig("Sens_AW_2_CP_vs_aw")

    # ── Sens_AW_3: mean(a) vs a_w  (self-consistent diagonal) ─────────────
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(aw_arr, meana_arr, "o-", color="#0173b2", lw=2, ms=5, label=r"$\bar{a}$ from LL")
    ax.plot(aw_arr, aw_arr, "--", color="#949494", lw=1.5,
            label=r"$\bar{a} = a_w$  (self-consistent line)")
    if has_sc:
        ax.axvline(sc_aw, color="#029e73", ls=":", lw=2, label=rf"Self-consistent $a_w = {sc_aw:.3f}$")
        ax.scatter([sc_aw], [sc_aw], color="#029e73", s=70, zorder=5)
    ax.set_xlabel(r"Input $a_w$ [-]"); ax.set_ylabel(r"$\bar{a}$ [-]")
    ax.legend(fontsize=font_size_big); ax.grid(True)
    fig.tight_layout(); _savefig("Sens_AW_3_mean_a_vs_aw")

    # ── Sens_AW_4: residual (mean(a) − a_w) vs a_w ────────────────────────
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(aw_arr, resid_arr, "o-", color="#d55e00", lw=2, ms=5)
    ax.axhline(0, color="#949494", ls="--", lw=1.5)
    if has_sc:
        ax.axvline(sc_aw, color="#029e73", ls=":", lw=2, label=rf"Zero crossing $a_w = {sc_aw:.3f}$")
        ax.scatter([sc_aw], [0.0], color="#029e73", s=70, zorder=5)
        ax.legend(fontsize=font_size_big)
    ax.set_xlabel(r"Input $a_w$ [-]"); ax.set_ylabel(r"Residual $\bar{a} - a_w$ [-]")
    ax.grid(True)
    fig.tight_layout(); _savefig("Sens_AW_4_residual_vs_aw")

    # ── Sens_AW_5..8: spanwise distributions with direction arrows ────────
    for qty_col, ylabel, fname, use_meana in [
            (0, r"$a$ [-]",                                          "Sens_AW_5_axial_induction_vs_rR", True),
            (5, r"$\Gamma$ [m$^2$/s]",                                "Sens_AW_6_circulation_vs_rR",     False),
            (3, r"$C_n = F_n\,/\,(\frac{1}{2}\rho U_\infty^2 R)$ [-]", "Sens_AW_7_normal_loading_vs_rR",  False),
            (7, r"$\phi$ [deg]",                                      "Sens_AW_8_inflow_angle_vs_rR",    False)]:
        fig, ax = plt.subplots(figsize=(9, 5))
        x_list, y_list = [], []
        for idx, (a_w, res) in enumerate(zip(aw_arr, aw_res)):
            if res is None:
                continue
            y = res[:, qty_col] / norm_val if qty_col == 3 else res[:, qty_col]
            if use_meana:
                lbl = rf"$a_w={a_w:.2f}$  $\bar{{a}}={meana_arr[idx]:.3f}$"
            else:
                ct  = ct_arr[idx] if idx < len(ct_arr) else float("nan")
                lbl = rf"$a_w={a_w:.2f}$  $C_T={ct:.3f}$"
            ax.plot(res[:, 2], y, color=_sens_color(idx), lw=1.8, label=lbl)
            x_list.append(res[:, 2]); y_list.append(y)
        ax.set_xlabel("r/R"); ax.set_ylabel(ylabel)
        ax.legend(fontsize=font_size_medium, bbox_to_anchor=(1.01, 1), loc="upper left")
        ax.grid(True); fig.tight_layout()
        _dir  = 'up' if qty_col == 0 else 'down'
        _xpos = {0: 0.26, 5: 0.39, 3: 0.75, 7: 0.26}.get(qty_col, None)
        _annotate_increasing_direction(ax, x_list, y_list,
                                       label=r"increasing $a_w$",
                                       color="#555555",
                                       force_direction=_dir, x_pos=_xpos)
        _savefig(fname)
else:
    print("    [SKIP] a_w sensitivity arrays not found in LL npz")

# ---------------------------------------------------------------------------
# 5.2  Blade discretisation  N + cosine/constant spacing
# ---------------------------------------------------------------------------
print("\n  5.2 — blade discretisation (N, spacing)")

N_avail = [int(n) for n in sens_N_vals] if len(sens_N_vals) > 0 else []

if N_avail:
    # Recompute scalar CT/CP from the stored result arrays (both spacings)
    cos_N = [N for N in N_avail if _disc_res(N, "cosine")   is not None]
    con_N = [N for N in N_avail if _disc_res(N, "constant") is not None]

    ct_cos = np.array([_ct_cp_from_res(_disc_res(N, "cosine"),   8, "cosine")[0]   for N in cos_N])
    cp_cos = np.array([_ct_cp_from_res(_disc_res(N, "cosine"),   8, "cosine")[1]   for N in cos_N])
    ct_con = np.array([_ct_cp_from_res(_disc_res(N, "constant"), 8, "constant")[0] for N in con_N])
    cp_con = np.array([_ct_cp_from_res(_disc_res(N, "constant"), 8, "constant")[1] for N in con_N])

    # ── a1: C_n vs r/R, cosine, sweep of N ────────────────────────────────
    fig, ax = plt.subplots(figsize=(8, 5))
    for idx, N in enumerate(cos_N):
        res = _disc_res(N, "cosine")
        ct  = _ct_cp_from_res(res, 8, "cosine")[0]
        ax.plot(res[:, 2], res[:, 3] / norm_val, color=_sens_color(idx), lw=2,
                label=rf"N={N}  $C_T={ct:.3f}$")
    ax.set_xlabel("r/R"); ax.set_ylabel(r"$C_n$ [-]")
    ax.legend(fontsize=font_size_medium); ax.grid(True)
    fig.tight_layout(); _savefig("Sens_Disc_a1_Cn_panel_count_cosine")

    # ── a2: a vs r/R, cosine, sweep of N ──────────────────────────────────
    fig, ax = plt.subplots(figsize=(8, 5))
    for idx, N in enumerate(cos_N):
        res = _disc_res(N, "cosine")
        cp  = _ct_cp_from_res(res, 8, "cosine")[1]
        ax.plot(res[:, 2], res[:, 0], color=_sens_color(idx), lw=2,
                label=rf"N={N}  $C_P={cp:.3f}$")
    ax.set_xlabel("r/R"); ax.set_ylabel(r"$a$ [-]")
    ax.legend(fontsize=font_size_medium); ax.grid(True)
    fig.tight_layout(); _savefig("Sens_Disc_a2_a_panel_count_cosine")

    # ── b1 / b2: cosine vs constant at the baseline N ─────────────────────
    N_ref = N_PANELS if (_disc_res(N_PANELS, "cosine") is not None) else (cos_N[-1] if cos_N else None)
    if N_ref is not None:
        fig, ax = plt.subplots(figsize=(8, 5))
        for dist in ("cosine", "constant"):
            res = _disc_res(N_ref, dist)
            if res is None:
                continue
            st = _DIST_STYLE[dist]
            ct = _ct_cp_from_res(res, 8, dist)[0]
            ax.plot(res[:, 2], res[:, 3] / norm_val, color=st["color"], lw=2, ls=st["ls"],
                    label=rf"{st['label']}  $C_T={ct:.3f}$")
        ax.set_xlabel("r/R"); ax.set_ylabel(r"$C_n$ [-]")
        ax.legend(fontsize=font_size_medium); ax.grid(True)
        fig.tight_layout(); _savefig("Sens_Disc_b1_Cn_cosine_vs_constant")

        fig, ax = plt.subplots(figsize=(8, 5))
        for dist in ("cosine", "constant"):
            res = _disc_res(N_ref, dist)
            if res is None:
                continue
            st = _DIST_STYLE[dist]
            cp = _ct_cp_from_res(res, 8, dist)[1]
            ax.plot(res[:, 2], res[:, 0], color=st["color"], lw=2, ls=st["ls"],
                    label=rf"{st['label']}  $C_P={cp:.3f}$")
        ax.set_xlabel("r/R"); ax.set_ylabel(r"$a$ [-]")
        ax.legend(fontsize=font_size_medium); ax.grid(True)
        fig.tight_layout(); _savefig("Sens_Disc_b2_a_cosine_vs_constant")

    # ── f1 / f2: multi-N cosine-vs-constant overlay with shaded band ──────
    _CMP_N = [N for N in (5, 20, 70)
              if _disc_res(N, "cosine") is not None and _disc_res(N, "constant") is not None]
    if _CMP_N:
        for zoom, fname in [(False, "Sens_Disc_f1_Cn_cosine_vs_constant_multiN"),
                            (True,  "Sens_Disc_f2_Cn_cosine_vs_constant_multiN_zoom")]:
            fig, ax = plt.subplots(figsize=(9, 5.5))
            for ci, N in enumerate(_CMP_N):
                col = _CB_PALETTE[ci]
                res_cos = _disc_res(N, "cosine")
                res_con = _disc_res(N, "constant")
                CT_cos = _ct_cp_from_res(res_cos, 8, "cosine")[0]
                CT_con = _ct_cp_from_res(res_con, 8, "constant")[0]

                rR_cos, Cn_cos = res_cos[:, 2], res_cos[:, 3] / norm_val
                rR_con, Cn_con = res_con[:, 2], res_con[:, 3] / norm_val
                Cn_con_on_cos  = np.interp(rR_cos, rR_con, Cn_con)
                ax.fill_between(rR_cos, Cn_cos, Cn_con_on_cos,
                                where=(Cn_con_on_cos > Cn_cos),
                                color=col, alpha=0.12, zorder=1, interpolate=True)
                ax.plot(rR_cos, Cn_cos, color=col, lw=2.0, ls="-", marker="o", ms=4,
                        zorder=3, label=rf"$N={N}$ cosine  $C_T={CT_cos:.3f}$")
                ax.plot(rR_con, Cn_con, color=col, lw=2.0, ls="--", marker="s", ms=4,
                        alpha=0.55, zorder=2, label=rf"$N={N}$ constant  $C_T={CT_con:.3f}$")
            ax.set_xlabel("r/R")
            ax.set_ylabel(r"$C_n = F_n\,/\,(\frac{1}{2}\rho U_\infty^2 R)$ [-]")
            ax.grid(True)
            if zoom:
                ax.set_xlim(0.7, 1.0)
                res_fine = _disc_res(_CMP_N[-1], "cosine")
                mask = res_fine[:, 2] >= 0.7
                y_tip = res_fine[mask, 3] / norm_val
                if y_tip.size:
                    ax.set_ylim(0.9 * float(np.min(y_tip)), 1.1 * float(np.max(y_tip)))
            ax.legend(fontsize=font_size_medium, loc="upper left")
            ax.text(0.02, 0.02, "Shaded band: constant $>$ cosine\n(over-predicted loading)",
                    transform=ax.transAxes, fontsize=font_size_medium, va="bottom", ha="left",
                    bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="#949494", alpha=0.85))
            fig.tight_layout(); _savefig(fname)

    # ── c1 / c2: CT and CP convergence vs N ───────────────────────────────
    for arr_cos, arr_con, ylabel, fname, ttl in [
            (ct_cos, ct_con, r"$C_T$ [-]", "Sens_Disc_c1_CT_convergence_vs_N", "CT"),
            (cp_cos, cp_con, r"$C_P$ [-]", "Sens_Disc_c2_CP_convergence_vs_N", "CP")]:
        fig, ax = plt.subplots(figsize=(8, 5))
        st = _DIST_STYLE["cosine"]
        ax.plot(cos_N, arr_cos, ls=st["ls"], color=st["color"], lw=2, marker=st["marker"],
                ms=6, label="Cosine")
        st = _DIST_STYLE["constant"]
        ax.plot(con_N, arr_con, ls=st["ls"], color=st["color"], lw=2, marker=st["marker"],
                ms=6, label="Constant")
        ax.axvline(N_PANELS, color="#949494", ls=":", lw=1.2, label=rf"Baseline $N={N_PANELS}$")
        ax.set_xlabel(r"$N_\mathrm{panels}$ [-]"); ax.set_ylabel(ylabel)
        ax.legend(fontsize=font_size_big); ax.grid(True)
        fig.tight_layout(); _savefig(fname)

    # ── d1: relative error vs N (ref = finest cosine) ─────────────────────
    if cos_N:
        N_ref_conv = cos_N[-1]
        ct_ref = ct_cos[-1]; cp_ref = cp_cos[-1]

        def _pct_err(arr, ref):
            e = np.abs(arr - ref) / abs(ref) * 100.0
            return np.where(e == 0, np.nan, e)

        fig, ax = plt.subplots(figsize=(8, 5))
        scos = _DIST_STYLE["cosine"]; scon = _DIST_STYLE["constant"]
        ax.semilogy(cos_N, _pct_err(ct_cos, ct_ref), ls="-",  color=scos["color"], lw=2,
                    marker="o", label=r"$\epsilon_{C_T}$ cosine")
        ax.semilogy(cos_N, _pct_err(cp_cos, cp_ref), ls="--", color=scos["color"], lw=2,
                    marker="o", alpha=0.6, label=r"$\epsilon_{C_P}$ cosine")
        ax.semilogy(con_N, _pct_err(ct_con, ct_ref), ls="-",  color=scon["color"], lw=2,
                    marker="s", label=r"$\epsilon_{C_T}$ constant")
        ax.semilogy(con_N, _pct_err(cp_con, cp_ref), ls="--", color=scon["color"], lw=2,
                    marker="s", alpha=0.6, label=r"$\epsilon_{C_P}$ constant")
        ax.axvline(N_PANELS, color="#949494", ls=":", lw=1.2, label=rf"Baseline $N={N_PANELS}$")
        ax.axvline(N_ref_conv, color="#444", ls="-.", lw=1.2, label=rf"Reference (finest) $N={N_ref_conv}$")
        ax.set_xlabel(r"$N_\mathrm{panels}$ [-]")
        ax.set_ylabel(r"Relative error w.r.t. finest cosine [%]")
        ax.legend(fontsize=font_size_small); ax.grid(True, which="both")
        fig.tight_layout(); _savefig("Sens_Disc_d1_error_vs_N")

    print("    [NOTE] Sens_Disc_d2/e1/e2 (timing) and converged/not-converged "
          "markers require data not saved to the npz — omitted.")
else:
    print("    [SKIP] discretisation sensitivity arrays not found in LL npz")

# ---------------------------------------------------------------------------
# 5.3  Azimuthal step  Δψ
# ---------------------------------------------------------------------------
print("\n  5.3 — azimuthal step (dpsi)")

if len(sens_dpsi_vals) > 0:
    dpsi_arr = np.asarray(sens_dpsi_vals, dtype=float)
    ct_arr   = np.asarray(sens_dpsi_CT,   dtype=float)
    cp_arr   = np.asarray(sens_dpsi_CP,   dtype=float)
    dpsi_res = [_dpsi_res(v) for v in dpsi_arr]

    # ── a / b: spanwise axial induction and normal loading ────────────────
    for qty_col, ylabel, fname in [
            (0, r"$a$ [-]",                                          "Sens_DPSI_a_axial_induction"),
            (3, r"$C_n = F_n\,/\,(\frac{1}{2}\rho U_\infty^2 R)$ [-]", "Sens_DPSI_b_normal_loading")]:
        fig, ax = plt.subplots(figsize=(8, 5))
        x_list, y_list = [], []
        for idx, (dp, res) in enumerate(zip(dpsi_arr, dpsi_res)):
            if res is None:
                continue
            y  = res[:, qty_col] / norm_val if qty_col == 3 else res[:, qty_col]
            ct = ct_arr[idx] if idx < len(ct_arr) else float("nan")
            ax.plot(res[:, 2], y, color=_sens_color(idx), lw=2,
                    label=rf"$\Delta\psi={dp:g}°$  $C_T={ct:.3f}$")
            x_list.append(res[:, 2]); y_list.append(y)
        ax.set_xlabel("r/R"); ax.set_ylabel(ylabel)
        ax.legend(fontsize=font_size_medium); ax.grid(True); fig.tight_layout()
        if fname == "Sens_DPSI_b_normal_loading":
            _annotate_increasing_direction(ax, x_list, y_list,
                                           label=r"increasing $\Delta\psi$",
                                           color="#555555",
                                           force_direction='left', y_pos=0.48)
        _savefig(fname)

    # ── c1 / c2: CT and CP vs Δψ ──────────────────────────────────────────
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(dpsi_arr, ct_arr, "o-", color="#0173b2", lw=2)
    ax.axvline(DPSI_DEG, color="#949494", ls="--", lw=1.2, label=rf"Baseline $\Delta\psi={DPSI_DEG:g}°$")
    ax.set_xlabel(r"$\Delta\psi$ [deg]"); ax.set_ylabel(r"$C_T$ [-]")
    ax.legend(fontsize=font_size_big); ax.grid(True)
    fig.tight_layout(); _savefig("Sens_DPSI_c1_CT_vs_dpsi")

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(dpsi_arr, cp_arr, "o-", color="#029e73", lw=2)
    ax.axvline(DPSI_DEG, color="#949494", ls="--", lw=1.2, label=rf"Baseline $\Delta\psi={DPSI_DEG:g}°$")
    ax.set_xlabel(r"$\Delta\psi$ [deg]"); ax.set_ylabel(r"$C_P$ [-]")
    ax.legend(fontsize=font_size_big); ax.grid(True)
    fig.tight_layout(); _savefig("Sens_DPSI_c2_CP_vs_dpsi")

    # ── d1: relative error vs Δψ (ref = finest = smallest Δψ, first entry) ─
    if len(ct_arr) > 0:
        ct_ref, cp_ref = ct_arr[0], cp_arr[0]
        err_CT = np.where(np.abs(ct_arr - ct_ref) == 0, np.nan,
                          np.abs(ct_arr - ct_ref) / abs(ct_ref) * 100.0)
        err_CP = np.where(np.abs(cp_arr - cp_ref) == 0, np.nan,
                          np.abs(cp_arr - cp_ref) / abs(cp_ref) * 100.0)
        fig, ax = plt.subplots(figsize=(8, 5))
        ax.semilogy(dpsi_arr, err_CT, "o-", color="#0173b2", lw=2, label=r"$\epsilon_{C_T}$ [%]")
        ax.semilogy(dpsi_arr, err_CP, "s-", color="#029e73", lw=2, label=r"$\epsilon_{C_P}$ [%]")
        ax.axvline(DPSI_DEG, color="#949494", ls="--", lw=1.2, label=rf"Baseline $\Delta\psi={DPSI_DEG:g}°$")
        ax.set_xlabel(r"$\Delta\psi$ [deg]"); ax.set_ylabel(r"Relative error w.r.t. finest case [%]")
        ax.legend(fontsize=font_size_big); ax.grid(True, which="both")
        fig.tight_layout(); _savefig("Sens_DPSI_d1_error_vs_dpsi")

    print("    [NOTE] Sens_DPSI_d2/e1/e2 (timing) require data not saved to the npz — omitted.")
else:
    print("    [SKIP] dpsi sensitivity arrays not found in LL npz")

# ---------------------------------------------------------------------------
# 5.4  Wake length  N_wake
# ---------------------------------------------------------------------------
print("\n  5.4 — wake length (N_wake)")

if len(sens_nwake_vals) > 0:
    nw_arr  = np.asarray(sens_nwake_vals, dtype=float)
    ct_arr  = np.asarray(sens_nwake_CT,   dtype=float)
    cp_arr  = np.asarray(sens_nwake_CP,   dtype=float)
    nw_res  = [_nwake_res(v) for v in nw_arr]
    nw_int  = [int(v) for v in nw_arr]

    _conv_tol = 0.005
    _ct_ref, _cp_ref = ct_arr[-1], cp_arr[-1]
    _nw_conv_CT = next((nw for nw, c in zip(nw_int, ct_arr) if abs(c - _ct_ref) < _conv_tol), nw_int[-1])
    _nw_conv_CP = next((nw for nw, c in zip(nw_int, cp_arr) if abs(c - _cp_ref) < _conv_tol), nw_int[-1])

    # ── a / b: spanwise axial induction and normal loading ────────────────
    for qty_col, ylabel, fname in [
            (0, r"$a$ [-]",                                          "Sens_Wake_a_axial_induction"),
            (3, r"$C_n = F_n\,/\,(\frac{1}{2}\rho U_\infty^2 R)$ [-]", "Sens_Wake_b_normal_loading")]:
        fig, ax = plt.subplots(figsize=(8, 5))
        x_list, y_list = [], []
        for idx, (nw, res) in enumerate(zip(nw_int, nw_res)):
            if res is None:
                continue
            y  = res[:, qty_col] / norm_val if qty_col == 3 else res[:, qty_col]
            ct = ct_arr[idx] if idx < len(ct_arr) else float("nan")
            cp = cp_arr[idx] if idx < len(cp_arr) else float("nan")
            ax.plot(res[:, 2], y, color=_sens_color(idx), lw=2,
                    label=rf"$N_{{wake}}={nw}$  $C_T={ct:.3f}$  $C_P={cp:.3f}$")
            x_list.append(res[:, 2]); y_list.append(y)
        ax.text(0.97, 0.97,
                rf"$C_T$ converged at $N_{{wake}}={_nw_conv_CT}$" + "\n"
                + rf"$C_P$ converged at $N_{{wake}}={_nw_conv_CP}$",
                transform=ax.transAxes, fontsize=font_size_medium, va="top", ha="right",
                bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="#949494", alpha=0.85))
        ax.set_xlabel("r/R"); ax.set_ylabel(ylabel)
        ax.legend(fontsize=font_size_small, bbox_to_anchor=(1.01, 1), loc="upper left")
        ax.grid(True); fig.tight_layout()
        if fname == "Sens_Wake_a_axial_induction":
            _annotate_increasing_direction(ax, x_list, y_list,
                                           label=r"increasing $N_{wake}$",
                                           color="#555555",
                                           force_direction='up', x_pos=0.51)
        _savefig(fname)

    # ── c1 / c2: CT and CP convergence vs N_wake ──────────────────────────
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(nw_int, ct_arr, "o-", color="#0173b2", lw=2)
    ax.axvline(_nw_conv_CT, color="#949494", ls="--", lw=1.2, label=rf"Converged at $N_{{wake}}={_nw_conv_CT}$")
    ax.axhline(_ct_ref, color="#949494", ls=":", lw=1.0)
    ax.set_xlabel(r"Wake length $N_{wake}$ [rotations]"); ax.set_ylabel(r"$C_T$ [-]")
    ax.legend(fontsize=font_size_big); ax.grid(True)
    fig.tight_layout(); _savefig("Sens_Wake_c1_CT_convergence_vs_Nwake")

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(nw_int, cp_arr, "o-", color="#029e73", lw=2)
    ax.axvline(_nw_conv_CP, color="#949494", ls="--", lw=1.2, label=rf"Converged at $N_{{wake}}={_nw_conv_CP}$")
    ax.axhline(_cp_ref, color="#949494", ls=":", lw=1.0)
    ax.set_xlabel(r"Wake length $N_{wake}$ [rotations]"); ax.set_ylabel(r"$C_P$ [-]")
    ax.legend(fontsize=font_size_big); ax.grid(True)
    fig.tight_layout(); _savefig("Sens_Wake_c2_CP_convergence_vs_Nwake")

    # ── d1: relative error vs N_wake (ref = longest wake) ─────────────────
    err_CT = np.where(np.abs(ct_arr - _ct_ref) == 0, np.nan,
                      np.abs(ct_arr - _ct_ref) / abs(_ct_ref) * 100.0)
    err_CP = np.where(np.abs(cp_arr - _cp_ref) == 0, np.nan,
                      np.abs(cp_arr - _cp_ref) / abs(_cp_ref) * 100.0)
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.semilogy(nw_int, err_CT, "o-", color="#0173b2", lw=2, label=r"$\epsilon_{C_T}$ [%]")
    ax.semilogy(nw_int, err_CP, "s-", color="#029e73", lw=2, label=r"$\epsilon_{C_P}$ [%]")
    ax.axvline(N_WAKE, color="#949494", ls="--", lw=1.2, label=rf"Baseline $N_{{wake}}={N_WAKE}$")
    ax.axvline(nw_int[-1], color="#444", ls="-.", lw=1.2, label=rf"Reference $N_{{wake}}={nw_int[-1]}$")
    ax.set_xlabel(r"Wake length $N_{wake}$ [rotations]")
    ax.set_ylabel(r"Relative error w.r.t. longest wake [%]")
    ax.legend(fontsize=font_size_big); ax.grid(True, which="both")
    fig.tight_layout(); _savefig("Sens_Wake_d1_error_vs_Nwake")

    print("    [NOTE] Sens_Wake_d2/e1/e2 (timing) require data not saved to the npz — omitted.")
else:
    print("    [SKIP] N_wake sensitivity arrays not found in LL npz")

# =============================================================================
# 6.  SUMMARY
# =============================================================================

print("\n" + "=" * 60)
print(f"All plots saved to: {OUT_DIR}")
print("=" * 60)
print("\nFile list:")
for f in sorted(os.listdir(OUT_DIR)):
    if f.endswith(".pdf"):
        print(f"  {f}")